In [142]:

# !pip install numpy 

import numpy as np 
import pandas as pd


array = np.arange(18)

array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [79]:
#creating a 2 d array 
array.reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [143]:
arry = np.arange(60)
arry.reshape(3,2,10)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]])

In [144]:
k = arry

k.reshape(-1)

k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [145]:
array =  np.arange(18).reshape(2,3,3)
array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [146]:
#slicing in 2d array

array[1:,1:3]

array([[[12, 13, 14],
        [15, 16, 17]]])

In [147]:
#iterate the array 

for  i in np.nditer(array):
    print(i,end = " " )

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 

In [148]:
for i,ele in enumerate(array):
    print('{} index element is {}'.format(i,ele))
    

0 index element is [[0 1 2]
 [3 4 5]
 [6 7 8]]
1 index element is [[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [149]:
#slcicing have three things [start:stop:step] in 2d array [which dimension index:row:column]

array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [150]:
array[1:,0:1,0:2]
                        

array([[[ 9, 10]]])

In [151]:
array.shape

(2, 3, 3)

In [152]:
array[0:,0:2,0:2]

array([[[ 0,  1],
        [ 3,  4]],

       [[ 9, 10],
        [12, 13]]])

In [153]:
sample = np.arange(24).reshape(3,2,4)

In [154]:
sample

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [155]:
sample[:,:1,:]

array([[[ 0,  1,  2,  3]],

       [[ 8,  9, 10, 11]],

       [[16, 17, 18, 19]]])

In [156]:
sample

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [157]:
sample.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [158]:
np.concatenate(array,sample)


TypeError: only integer scalar arrays can be converted to a scalar index

In [159]:
array.shape

(2, 3, 3)

In [160]:
sample.shape

(3, 2, 4)

# using stacking in numpy 


In [161]:
a = np.arange(12)
b = np.arange(12,24)


In [162]:
#stack default axis is row 

np.stack((a,b))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [163]:

#hstack 

np.hstack((a,b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [164]:
np.stack((a,b),axis = 1)


array([[ 0, 12],
       [ 1, 13],
       [ 2, 14],
       [ 3, 15],
       [ 4, 16],
       [ 5, 17],
       [ 6, 18],
       [ 7, 19],
       [ 8, 20],
       [ 9, 21],
       [10, 22],
       [11, 23]])

In [165]:
a1 = a.reshape(2,6)

In [166]:
a2 = b.reshape(2,-1)

In [167]:
c =np.stack((a1,a2),axis = 2) #column wise stacking 
c

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15],
        [ 4, 16],
        [ 5, 17]],

       [[ 6, 18],
        [ 7, 19],
        [ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [168]:
c.shape

(2, 6, 2)

In [169]:
#sorting the array 
a3 = [109,12321,23,2,12,12]
k = np.where(a3 == 23 )

In [170]:
#axis = 1 take one row from one dimension and stack then together 

np.stack((a1,a2),axis = 1)

array([[[ 0,  1,  2,  3,  4,  5],
        [12, 13, 14, 15, 16, 17]],

       [[ 6,  7,  8,  9, 10, 11],
        [18, 19, 20, 21, 22, 23]]])

In [171]:
#axis = 1 take one dimesion at one time and stack them together one below the other 

np.stack((a1,a2),axis=0)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [183]:
a1 = [[1,2,2],[3,4,3]]
a2 = [[12,12,23],[1,2,4]]
np.concatenate((a1,a2),axis =1)

array([[ 1,  2,  2, 12, 12, 23],
       [ 3,  4,  3,  1,  2,  4]])