In [6]:
#numpy is basically a python package and it is known as numerical python 

#pandas is also a python package.

#it is used to store data of same type.

#a package is a collection of modules and library is a collection of packages


my_list = [1,2,3,4,5]
print(my_list)


[1, 2, 3, 4, 5]


In [7]:
print(type(my_list))

# print(my_list.ndim)

# print(my_list.shape)
# print(my_list.size)

#here we are got and error because my_list is not a nympy array it is simply a list.

<class 'list'>


In [32]:
import numpy as np 
array = np.array([1,2,0,-1,5],dtype = float)
array = np.array([1,2,0,-1,5],dtype = int)
array = np.array([1,2,0,-1,5],dtype = bool)
array = np.array([1,2,0,-1,5,6],dtype = str)
print(array)

['1' '2' '0' '-1' '5' '6']


In [30]:
print(type(array))

<class 'numpy.ndarray'>


In [55]:
new_array = array.reshape(2,3,-1) # 2 dimesional array with 3 rows and some sort of columns.
print(new_array)
new_array.size

[[['1']
  ['2']
  ['0']]

 [['-1']
  ['5']
  ['6']]]


6

In [56]:
x = range(34)
x

range(0, 34)

In [4]:
import numpy as np 

x = np.arange(18)
print(x)
print(x.ndim)
print(x.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
1
18


In [5]:
new_array1 = x.reshape(6,3,1)
print(new_array1)
print(new_array1.ndim)

[[[ 0]
  [ 1]
  [ 2]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]]

 [[15]
  [16]
  [17]]]
3


In [6]:
new_array1.itemsize

4

In [9]:
mat1 = np.array([[1,2],[3,4]])
print(mat1)
mat2 = np.array([[3,4],[5,6]])
print(mat2)

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]


In [10]:
mat1+mat2

array([[ 4,  6],
       [ 8, 10]])

In [11]:
mat1-mat2

array([[-2, -2],
       [-2, -2]])

In [12]:
mat1 * mat2

array([[ 3,  8],
       [15, 24]])

In [13]:
mat1/mat2

array([[0.33333333, 0.5       ],
       [0.6       , 0.66666667]])

In [14]:
np.sum(mat1)

10

In [15]:
np.sum(mat1,axis = 0)

array([4, 6])

In [16]:
np.sum(mat2,axis =1)

array([ 7, 11])

In [19]:
s = "learning is fun"
s.isalpha() # the string is having alphabets and numbers also 

False

In [26]:
s.isnumeric()
s.capitalize()
s.title()
s.swapcase()


'LEARNING IS FUN'

In [29]:
k = "{} {}.{}.".format('aryan','pvt','limited')
k

'aryan pvt.limited.'

In [32]:
dir(k)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [37]:
from array import *
new_array = array('i',[1,2,3,4,5])
new_array2 = array('f',[1,2,3,2])
print(new_array2)

array('f', [1.0, 2.0, 3.0, 2.0])


In [49]:
a1 = np.arange(start = 1,stop = 9).reshape(2,4)
a2 = np.arange(start = 1,stop = 9).reshape(2,4)
print(a1.shape)
print(a2.shape)
print(np.add(a1,a2))

(2, 4)
(2, 4)
[[ 2  4  6  8]
 [10 12 14 16]]


In [62]:
mat = np.matrix("5, 9, 10; 2, 5, 4; 1, 9, 8; 2, 6, 8")
mat1 = np.matrix("1, 2, 3")
mat2 = np.insert(mat, 1, mat1, axis= 0)
print(mat2)


[[ 5  9 10]
 [ 1  2  3]
 [ 2  5  4]
 [ 1  9  8]
 [ 2  6  8]]


In [77]:
#set is mutable in python whereas frozen set is immutable in python 
# tup = (1,2,3,4)+(1)
tup = (1,2,3,3)+(1,2)